### ISSUE TITLE
executable-ruby's executable "setup" conflicts with wisper

### ISSUE THREAD

**Issue by AndyObtiva** [alx3dev/executable-ruby#3]
Hi,

I just installed the latest version of executable-ruby, and I got this message given that I have the wisper gem installed too:

```
executable-ruby's executable "setup" conflicts with wisper
```

I think naming a binary `setup` is too generic and prone to conflicting with other gems (that happen to also have a badly named generic binary). 

Maybe call it `exer-setup` or something else that is unique?

**Comment by alx3dev** [comment]
This one will be closed because I must edit gem binary script from scratch.

**Comment by AndyObtiva** [comment]
By the way, the etiquette is usually to close an issue only once it has been addressed (a release is made or code/fix/advice is fully provided), using the issue as a way of motivation towards doing the work. Otherwise, the software engineer might close the ticket and not get the work done, losing out on the motivation factor. It is important to be patient instead of closing the ticket right away. Patience is good.
