### ISSUE TITLE
bin/setup: line 9: wget: command not found

### ISSUE THREAD

**Issue by AndyObtiva** [alx3dev/executable-ruby#5]
So, I cloned executable-ruby into a local directory and then ran `bin/setup`, and here is what I got (BTW, the repo URL is mispelled in the README as `git clone https://www.githib.com/alx3dev/executable-ruby` having `githib` instead of `github`):

```
bundle install
+ bundle install
Resolving dependencies...
Using bundler 2.3.1
Using executable-ruby 0.1.2 from source at `.` and installing its executables
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

# download golang for linux
wget https://go.dev/dl/go1.17.8.linux-amd64.tar.gz
+ wget https://go.dev/dl/go1.17.8.linux-amd64.tar.gz
bin/setup: line 9: wget: command not found
```

I realize I need to have `wget` installed on my mac (I am running Catalina 10.16.7 on an x64 Intel CPU), but I figured since you are installing dependencies automatically as part of setting up executable-ruby, maybe you can detect if `wget` is installed or not, and if not, you can install `wget` too?

**Comment by alx3dev** [comment]
Thank you, I edited setup script to check for `wget` and ask for OS. Linux install with `apt`, while mac install with `brew`. It's in branch `in-development`. Just one question, does `brew` also accept `-y` flag, as `apt`?

**Comment by AndyObtiva** [comment]
> Just one question, does brew also accept -y flag, as apt?

I am not sure why you're asking me that when you could have just run "brew install --help" or looked up its [command documentation](https://docs.brew.sh/Manpage) and found the answer for yourself faster than asking me.

As the executable-ruby library author, you are supposed to become an expert on `brew` and all the other tools you're using, so you should know the answers without asking for help.

There are times when asking for help is good (like when needing to distribute work) and other times when being patient and doing due diligence is better if help is already available in documentation or open-source-code.

**Comment by alx3dev** [comment]
Just because I don't have a brew, I am not on my computer and I can't open pages that I usually can. I don't use Mac and brew and I don't see it as a problem, because usaly I would just a command to see answer, but this time I just couldn't do that. Sorry for asking, I will avoid that in the future.

**Comment by AndyObtiva** [comment]
You may try to install [a Mac ISO](https://techsprobe.com/download-iso-file-of-macos-catalina-10-15-virtual-images/) and [a Windows ISO](https://www.microsoft.com/en-ca/software-download/windows10ISO) in a Virtual Machine software like [VirtualBox](https://www.virtualbox.org/) (that is how I got access to all operating systems) or use cloud services like https://www.macincloud.com/

I think it is important for you to have access to all platforms as the developer even if I could help you as a quality assurance tester on all platforms. That ensures you have a much shorter feedback cycle for most issues.

**Comment by alx3dev** [comment]
Yea I couldn't agree more, but in the time of writing I couldn't open anything related to `google.com`, or virtual machine, I've only had access to terminal without `brew`, and without access to install it.

**Comment by AndyObtiva** [comment]
Well, then you are not prepared properly enough to succeed at this time. 

Imagine me trying to write [glimmer-dsl-libui](https://github.com/AndyObtiva/glimmer-dsl-libui/) without having access to all of Mac, Windows, and Linux as platforms, or even the Internet or parts of the Internet, or if I kept making lame excuses instead of owning my issues and fixing responsibly without getting defensive. l'd be in the wrong position to work on the project idea in the first place and the project would have not won a [Fukuoka Ruby 2022 Special Award](https://andymaleh.blogspot.com/2022/02/glimmer-dsl-for-libui-wins-fukuoka-ruby.html)

I am not willing to commit my time to help someone who is not prepared enough to succeed. Please get your act together first, and then let me know once you are ready enough for me to test your work.

**Comment by alx3dev** [comment]
I was working, because of the closed network I wasn't able to access any resources at the time. I am really sorry that I asked for help (and help was to try to open it on Windows and mac, not to contribute or spend your time on any way). You really compare glimmer and few lines of code in `executable-ruby` ? Those two things can't be compared, ever. I am just one guy with one single laptop, so you can't expect from me any big project. Even if my knowledge is pretty big, seems like that is not much important in these days. Wish you all the best, over and out!
